//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BitkimiTaniEntities : DbContext
    {
        public BitkimiTaniEntities()
            : base("name=BitkimiTaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AraziBilgileri_tbl> AraziBilgileri_tbl { get; set; }
        public virtual DbSet<BitkiAd_tbl> BitkiAd_tbl { get; set; }
        public virtual DbSet<BitkiDetay_tbl> BitkiDetay_tbl { get; set; }
        public virtual DbSet<BitkiEkoloji_tbl> BitkiEkoloji_tbl { get; set; }
        public virtual DbSet<BitkiHastaliklari_tbl> BitkiHastaliklari_tbl { get; set; }
        public virtual DbSet<BitkiHastalikResimleri_Egitim_tbl> BitkiHastalikResimleri_Egitim_tbl { get; set; }
        public virtual DbSet<BitkiHastalikResimleri_Test_tbl> BitkiHastalikResimleri_Test_tbl { get; set; }
        public virtual DbSet<BitkiKullanim_tbl> BitkiKullanim_tbl { get; set; }
        public virtual DbSet<BitkiMineraller_tbl> BitkiMineraller_tbl { get; set; }
        public virtual DbSet<BitkiMorfoloji_tbl> BitkiMorfoloji_tbl { get; set; }
        public virtual DbSet<BitkiResimleri_Egitim_tbl> BitkiResimleri_Egitim_tbl { get; set; }
        public virtual DbSet<BitkiResimleri_Test_tbl> BitkiResimleri_Test_tbl { get; set; }
        public virtual DbSet<BitkiSistematigi_tbl> BitkiSistematigi_tbl { get; set; }
        public virtual DbSet<BitkiTanima_tbl> BitkiTanima_tbl { get; set; }
        public virtual DbSet<BitkiTur_tbl> BitkiTur_tbl { get; set; }
        public virtual DbSet<BitkiZararlilari_tbl> BitkiZararlilari_tbl { get; set; }
        public virtual DbSet<EkBilgiler_tbl> EkBilgiler_tbl { get; set; }
        public virtual DbSet<Ekip_tbl> Ekip_tbl { get; set; }
        public virtual DbSet<FavoriBitki_tbl> FavoriBitki_tbl { get; set; }
        public virtual DbSet<Gubre_tbl> Gubre_tbl { get; set; }
        public virtual DbSet<Hastalik_BesinEksikligi_tbl> Hastalik_BesinEksikligi_tbl { get; set; }
        public virtual DbSet<HastalikAdlari_tbl> HastalikAdlari_tbl { get; set; }
        public virtual DbSet<HastalikSiniflari_tbl> HastalikSiniflari_tbl { get; set; }
        public virtual DbSet<HavaDurumu_tbl> HavaDurumu_tbl { get; set; }
        public virtual DbSet<HavaDurumuWebAdresi_tbl> HavaDurumuWebAdresi_tbl { get; set; }
        public virtual DbSet<ilce_tbl> ilce_tbl { get; set; }
        public virtual DbSet<Kullanici_tbl> Kullanici_tbl { get; set; }
        public virtual DbSet<KullaniciRoles_tbl> KullaniciRoles_tbl { get; set; }
        public virtual DbSet<KullaniciSosyalMedya_tbl> KullaniciSosyalMedya_tbl { get; set; }
        public virtual DbSet<KullaniciYorumlari_tbl> KullaniciYorumlari_tbl { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<MahsulBilgisi_tbl> MahsulBilgisi_tbl { get; set; }
        public virtual DbSet<Mail_tbl> Mail_tbl { get; set; }
        public virtual DbSet<NumuneKonum_tbl> NumuneKonum_tbl { get; set; }
        public virtual DbSet<Roles_tbl> Roles_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ToprakAnalizi_tbl> ToprakAnalizi_tbl { get; set; }
        public virtual DbSet<ToprakMineral_tbl> ToprakMineral_tbl { get; set; }
        public virtual DbSet<ToprakMineralleri_tbl> ToprakMineralleri_tbl { get; set; }
        public virtual DbSet<Uretim_tbl> Uretim_tbl { get; set; }
        public virtual DbSet<versiyon_tbl> versiyon_tbl { get; set; }
        public virtual DbSet<Yaprak_AyasinaGore_tbl> Yaprak_AyasinaGore_tbl { get; set; }
        public virtual DbSet<Yaprak_Damarimsi_tbl> Yaprak_Damarimsi_tbl { get; set; }
        public virtual DbSet<Yaprak_DizlislerineGore_tbl> Yaprak_DizlislerineGore_tbl { get; set; }
        public virtual DbSet<Yaprak_KenarlarinaGore_tbl> Yaprak_KenarlarinaGore_tbl { get; set; }
        public virtual DbSet<YaprakTipi_tbl> YaprakTipi_tbl { get; set; }
        public virtual DbSet<YaprakTuru_tbl> YaprakTuru_tbl { get; set; }
        public virtual DbSet<ZararliHakkindaBilgi_tbl> ZararliHakkindaBilgi_tbl { get; set; }
        public virtual DbSet<ZararlilarinResim_Egitim_tbl> ZararlilarinResim_Egitim_tbl { get; set; }
        public virtual DbSet<ZararlilarinResim_Test_tbl> ZararlilarinResim_Test_tbl { get; set; }
        public virtual DbSet<ZararliTuru_tbl> ZararliTuru_tbl { get; set; }
        public virtual DbSet<il_tbl> il_tbl { get; set; }
    }
}
