//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiAd_tbl
    {
        public int ID { get; set; }
        public string TurkceAdi { get; set; }
        public string IngilizceAdi { get; set; }
        public string LatinceAdi { get; set; }
        public string SinonimAdi { get; set; }
        public string YerelAdlar { get; set; }
        public byte[] KayitVersiyon { get; set; }
        public Nullable<short> Aktif { get; set; }
        public Nullable<int> Silik { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
    }
}
