//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiMineraller_tbl
    {
        public int ID { get; set; }
        public Nullable<int> BitkiAd_ID { get; set; }
        public string MineralAdi { get; set; }
        public string MineralHakkindaBilgiler { get; set; }
        public string Nem { get; set; }
        public string MineralMinDegeri { get; set; }
        public string MineralMaxDegeri { get; set; }
        public string TopraktaBulunmasiGerekenMineraller { get; set; }
        public string AnalizBirimi { get; set; }
    }
}
