//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiHastaliklari_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiHastaliklari_tbl()
        {
            this.BitkiDetay_tbl = new HashSet<BitkiDetay_tbl>();
        }
    
        public int ID { get; set; }
        public string BitkiHastalikSinifi { get; set; }
        public string BitkiHastalikAdi { get; set; }
        public Nullable<int> HastalikResimleri_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiDetay_tbl> BitkiDetay_tbl { get; set; }
        public virtual BitkiHastalikResimleri_Test_tbl BitkiHastalikResimleri_Test_tbl { get; set; }
    }
}
