//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiResimleri_Test_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiResimleri_Test_tbl()
        {
            this.BitkiDetay_tbl = new HashSet<BitkiDetay_tbl>();
        }
    
        public int ID { get; set; }
        public string Genel_BitkiResimleri { get; set; }
        public string Cicek_BitkiResimleri { get; set; }
        public string Yaprak_BitkiResimleri { get; set; }
        public string Govde_BitkiResimleri { get; set; }
        public string Meyvesi_BitkiResimleri { get; set; }
        public string BegeniPuani { get; set; }
        public string BegenmemePuani { get; set; }
        public string FavoriPuani { get; set; }
        public Nullable<short> Aktif { get; set; }
        public Nullable<int> Silik { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<System.DateTime> GuncellenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiDetay_tbl> BitkiDetay_tbl { get; set; }
    }
}
