//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiDetay_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiDetay_tbl()
        {
            this.FavoriBitki_tbl = new HashSet<FavoriBitki_tbl>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Bitki_Ad_ID { get; set; }
        public Nullable<int> Bitki_Sistematik_ID { get; set; }
        public Nullable<int> Bitki_Morfoloji_ID { get; set; }
        public Nullable<int> Bitki_Ekoloji_ID { get; set; }
        public Nullable<int> Bitki_Uretim_ID { get; set; }
        public Nullable<int> Bitki_Tanima_ID { get; set; }
        public Nullable<int> Bitki_Kullanim_ID { get; set; }
        public Nullable<int> Bitki_EkBilgiler_ID { get; set; }
        public Nullable<int> Bitki_Hastaliklari_ID { get; set; }
        public Nullable<int> Bitki_Zararlilari_ID { get; set; }
        public Nullable<int> BilgiEkleyenKullanici_ID { get; set; }
        public Nullable<int> BitkiResimleri_ID { get; set; }
        public Nullable<System.DateTime> Bitki_EklenmeZamani { get; set; }
        public string Konum { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<bool> Güncelle { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<bool> Ekle { get; set; }
        public Nullable<bool> YazmaYetkisi { get; set; }
    
        public virtual BitkiHastaliklari_tbl BitkiHastaliklari_tbl { get; set; }
        public virtual BitkiKullanim_tbl BitkiKullanim_tbl { get; set; }
        public virtual BitkiMorfoloji_tbl BitkiMorfoloji_tbl { get; set; }
        public virtual BitkiResimleri_Test_tbl BitkiResimleri_Test_tbl { get; set; }
        public virtual BitkiSistematigi_tbl BitkiSistematigi_tbl { get; set; }
        public virtual BitkiTanima_tbl BitkiTanima_tbl { get; set; }
        public virtual BitkiZararlilari_tbl BitkiZararlilari_tbl { get; set; }
        public virtual EkBilgiler_tbl EkBilgiler_tbl { get; set; }
        public virtual BitkiEkoloji_tbl BitkiEkoloji_tbl { get; set; }
        public virtual Uretim_tbl Uretim_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriBitki_tbl> FavoriBitki_tbl { get; set; }
    }
}
