//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitkiMorfoloji_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BitkiMorfoloji_tbl()
        {
            this.BitkiDetay_tbl = new HashSet<BitkiDetay_tbl>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BitkiAd_ID { get; set; }
        public string GenelBilgi { get; set; }
        public string CiceklenmeZamani { get; set; }
        public Nullable<byte> YaprakTipi { get; set; }
        public string Kokusu { get; set; }
        public string EnDusukRakim { get; set; }
        public string EnYuksekRakim { get; set; }
        public string Budama { get; set; }
        public string MeyveTipi { get; set; }
        public string DalFormu { get; set; }
        public string Cicek { get; set; }
        public string CicekRengi { get; set; }
        public string CiceklilikSuresi { get; set; }
        public string EnUzunBoy { get; set; }
        public string EnKisaBoy { get; set; }
        public string OrtalamaBoy { get; set; }
        public string YaprakDizilisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiDetay_tbl> BitkiDetay_tbl { get; set; }
    }
}
