//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekip_tbl
    {
        public int ID { get; set; }
        public string EkipAdi { get; set; }
        public string EkipKonumAdresi { get; set; }
        public string Kullanici_ID { get; set; }
        public string OlusturmaTarihi { get; set; }
        public Nullable<int> Bitki_ID { get; set; }
        public string EkipIletisimTelefon { get; set; }
        public string EMail { get; set; }
    }
}
