//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriBitki_tbl
    {
        public int ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> Bitki_ID { get; set; }
        public Nullable<byte> Degerlendirmeler { get; set; }
        public byte[] EklenmeTarihi { get; set; }
    
        public virtual BitkiDetay_tbl BitkiDetay_tbl { get; set; }
        public virtual Kullanici_tbl Kullanici_tbl { get; set; }
    }
}
