//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gubre_tbl
    {
        public int Id { get; set; }
        public Nullable<int> UrunBilgisi_ID { get; set; }
        public Nullable<int> Numune_ID { get; set; }
        public Nullable<int> AraziBilgileri_ID { get; set; }
        public string GubreAnalizi { get; set; }
        public string EkimGubresiTavsiyesi { get; set; }
        public Nullable<System.DateTime> EkimGubresiTarih { get; set; }
        public string EkimGubresiMiktari { get; set; }
        public string UstGubreTavsiyesi { get; set; }
        public string UstGubreMiktari { get; set; }
        public string UstGubreTarih { get; set; }
        public string DonusumKatsayisi { get; set; }
    }
}
