//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavaDurumu_tbl
    {
        public int ID { get; set; }
        public string Sicaklik { get; set; }
        public string Yagis { get; set; }
        public string Nem { get; set; }
        public string Ruzgar { get; set; }
        public string DenizeIndirgenmisBasinc { get; set; }
        public string AktüelBasinc { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public string Tarih { get; set; }
        public Nullable<int> HavaDurumuWeb_ID { get; set; }
    }
}
