//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorAction { get; set; }
        public string ErrorDetail { get; set; }
        public string ErrorController { get; set; }
        public string ErrorTime { get; set; }
    }
}
