//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MahsulBilgisi_tbl
    {
        public int ID { get; set; }
        public Nullable<int> Bitki_ID { get; set; }
        public string TarimSekli { get; set; }
        public string HasatZamani { get; set; }
        public string DikimZamani { get; set; }
        public string OlgunlasmaSuresi { get; set; }
    }
}
