//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToprakMineralleri_tbl
    {
        public int ID { get; set; }
        public string AnalizAdi { get; set; }
        public string AnalizSonucu { get; set; }
        public string AnalizMinDegeri { get; set; }
        public string AnalizMaxDegeri { get; set; }
        public string Nem { get; set; }
        public string AnalizBirimi { get; set; }
        public string MineralHakkindaBilgi { get; set; }
    }
}
