//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToprakAnalizi_tbl
    {
        public int ID { get; set; }
        public string NumuneNo { get; set; }
        public Nullable<System.DateTime> NumuneTarihi { get; set; }
        public Nullable<int> AnalizID { get; set; }
        public Nullable<int> KonumID { get; set; }
        public Nullable<int> UrunBitki_ID { get; set; }
        public string Derinlik { get; set; }
    }
}
