//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uretim_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uretim_tbl()
        {
            this.BitkiDetay_tbl = new HashSet<BitkiDetay_tbl>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BitkiAd_ID { get; set; }
        public string VideoLinki { get; set; }
        public string UretimYontemleri { get; set; }
        public string CelikleUretim { get; set; }
        public string GelisimHizi { get; set; }
        public string BakimIhtiyaci { get; set; }
        public string SulamaYontemi { get; set; }
        public string TohumDikimDerinligi_Min { get; set; }
        public string TohumDikimDerinligi_Max { get; set; }
        public string AraziOlcusu { get; set; }
        public string SulamaTarihi { get; set; }
        public string RuzgarHizi { get; set; }
        public string OrtamSicakligi { get; set; }
        public string SogukKusak { get; set; }
        public string SicakKusak { get; set; }
        public string YillikSicaklikGunSayisi { get; set; }
        public string SoguyaDayaniklililkSicaklikAraligi { get; set; }
        public string MevsimineGore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitkiDetay_tbl> BitkiDetay_tbl { get; set; }
    }
}
