//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class versiyon_tbl
    {
        public int ID { get; set; }
        public string dizin { get; set; }
        public string versiyon { get; set; }
        public Nullable<System.DateTime> versiyonTarihi { get; set; }
        public string versiyonAciklama { get; set; }
        public Nullable<bool> aktif { get; set; }
    }
}
