//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yaprak_AyasinaGore_tbl
    {
        public int ID { get; set; }
        public Nullable<int> Bitki_ID { get; set; }
        public Nullable<bool> IgneYapraklilar { get; set; }
        public Nullable<bool> DikenliYapraklilar { get; set; }
        public Nullable<bool> OvalYapraklilar { get; set; }
        public Nullable<bool> SeritYapraklilar { get; set; }
        public Nullable<bool> SpatulYapraklilar { get; set; }
        public Nullable<bool> EtliYapraklilar { get; set; }
    }
}
