//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yaprak_KenarlarinaGore_tbl
    {
        public int ID { get; set; }
        public Nullable<int> Bitki_ID { get; set; }
        public Nullable<bool> DuzKenar { get; set; }
        public Nullable<bool> DisliKenar { get; set; }
        public Nullable<bool> BolmeliKenar { get; set; }
        public Nullable<bool> ParcaKenar { get; set; }
    }
}
