//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFull.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZararliHakkindaBilgi_tbl
    {
        public int ID { get; set; }
        public Nullable<byte> ZararliTuru_ID { get; set; }
        public string ZararlininAdi { get; set; }
        public string Resimleri { get; set; }
    }
}
